# Vial support
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes

# Desired features
AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
KEY_LOCK_ENABLE = yes

# Space savings
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
MUSIC_ENABLE = no
QMK_SETTINGS = no
COMBO_ENABLE = no
LTO_ENABLE = yes